
package vista;

import controlador.Main;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.Toolkit;

/**
 *
 * @author alsolis
 */
public class Configurar extends javax.swing.JFrame {

    /**
     * Creates new form Configurar
     */
    public Configurar() {
     
        initComponents();
        setBounds(800, 300, 473, 537);
        setResizable(false);
        this.setLocationRelativeTo(null);
        btn_atras.setOpaque(false);
        btn_atras.setContentAreaFilled(false);
        btn_atras.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text_modelo = new javax.swing.JTextField();
        text_pasajeros = new javax.swing.JTextField();
        text_sobrecargo = new javax.swing.JTextField();
        text_piloto = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_modelo.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        text_modelo.setBorder(null);
        text_modelo.setOpaque(false);
        text_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(text_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 30));

        text_pasajeros.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        text_pasajeros.setBorder(null);
        text_pasajeros.setOpaque(false);
        jPanel1.add(text_pasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));

        text_sobrecargo.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        text_sobrecargo.setBorder(null);
        text_sobrecargo.setOpaque(false);
        text_sobrecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sobrecargoActionPerformed(evt);
            }
        });
        jPanel1.add(text_sobrecargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 30));

        text_piloto.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        text_piloto.setBorder(null);
        text_piloto.setOpaque(false);
        jPanel1.add(text_piloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 30));

        btn_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Agregar.png"))); // NOI18N
        btn_ingresar.setOpaque(false);
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 50));

        btn_atras.setBorder(null);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configurar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_modeloActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        Main.mostrar_Inicio();
        Main.ocultar_Configurar();
        
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        Main.configurar_Inicio();    
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void text_sobrecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sobrecargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sobrecargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurar().setVisible(true);
            }
        });
    }

    public String getText_modelo() {
        return text_modelo.getText();
    }

    public void setText_modelo(JTextField text_modelo) {
        this.text_modelo = text_modelo;
    }

    public String getText_pasajeros() {
        return text_pasajeros.getText();
    }

    public void setText_pasajeros(JTextField text_pasajeros) {
        this.text_pasajeros = text_pasajeros;
    }

    public String getText_piloto() {
        return text_piloto.getText();
    }

    public void setText_piloto(JTextField text_piloto) {
        this.text_piloto = text_piloto;
    }

    public String getText_sobrecargo() {
        return text_sobrecargo.getText();
    }

    public void setText_sobrecargo(JTextField text_sobrecargo) {
        this.text_sobrecargo = text_sobrecargo;
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_modelo;
    private javax.swing.JTextField text_pasajeros;
    private javax.swing.JTextField text_piloto;
    private javax.swing.JTextField text_sobrecargo;
    // End of variables declaration//GEN-END:variables
}
